[project]
name = "anki-media-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=0.8.0",
    "aiohttp>=3.8.0",
    "beautifulsoup4>=4.11.0",
    "transformers>=4.21.0",
]
